version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::659461175365:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-U14MATEc8bpK"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::659461175365:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-7MmRuCVBVfrb"
cloudformation_execution_role = "arn:aws:iam::659461175365:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-WrXuNyQSRsa2"
artifacts_bucket = ""
image_repository = ""
region = "eu-west-2"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::659461175365:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-JG0jWZVFvgRN"
cloudformation_execution_role = "arn:aws:iam::659461175365:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-2VlWlt9uqSv4"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-5j7afvn1mr6r"
image_repository = ""
region = "eu-west-2"
